export const GLOBAL_CONSTANT = {
  MODEL_GROUP: "MODEL_GROUP",
  HELPER_GROUP: "HELPER_GROUP",
  MARK_LABEL_GROUP: "MARK_LABEL_GROUP",
  MARK_LABEL_INFO: "MARK_LABEL_INFO",
  BOX_HELPER: "BOX_HELPER",
  _ENV_: "_ENV_",
  _MARK_LABEL_: "_MARK_LABEL_",
  _ROAM_: "_ROAM_",
};
