export const testData1 = [
  {
    id: 1,
    name: "场景1",
    type: "场景",
    desc: "这是一个场景",
    imgUrl: "/common/images/test.jpg",
  },
  {
    id: 2,
    name: "场景2",
    type: "场景",
    desc: "这是一个场景",
    imgUrl: "/common/images/test.jpg",
  },
  {
    id: 3,
    name: "场景3",
    type: "场景",
    desc: "这是一个场景",
    imgUrl: "/common/images/test.jpg",
  },
  {
    id: 4,
    name: "场景4",
    type: "场景",
    desc: "这是一个场景",
    imgUrl: "/common/images/test.jpg",
  },
  {
    id: 5,
    name: "场景5",
    type: "场景",
    desc: "这是一个场景",
    imgUrl: " ",
  },
  {
    id: 6,
    name: "场景6",
    type: "场景",
    desc: "这是一个场景",
    imgUrl: " ",
  },
  {
    id: 7,
    name: "场景7",
    type: "场景",
    desc: "这是一个场景",
    imgUrl: " ",
  },
  {
    id: 8,
    name: "场景8",
    type: "场景",
    desc: "这是一个场景",
    imgUrl: " ",
  },
];

export const testData2 = [
  {
    id: 1,
    name: "模型1",
    type: "模型",
    desc: "这是一个场景",
    imgUrl: "/common/images/test.jpg",
  },
  {
    id: 2,
    name: "模型2",
    type: "模型",
    desc: "这是一个场景",
    imgUrl: "/common/images/test.jpg",
  },
  {
    id: 3,
    name: "模型3",
    type: "模型",
    desc: "这是一个场景",
    imgUrl: "/common/images/test.jpg",
  },
  {
    id: 4,
    name: "模型4",
    type: "模型",
    desc: "这是一个场景",
    imgUrl: " ",
  },
  {
    id: 5,
    name: "模型5",
    type: "模型",
    desc: "这是一个场景",
    imgUrl: " ",
  },
  {
    id: 6,
    name: "模型6",
    type: "模型",
    desc: "这是一个场景",
    imgUrl: " ",
  },
  {
    id: 7,
    name: "模型7",
    type: "模型",
    desc: "这是一个场景",
    imgUrl: " ",
  },
  {
    id: 8,
    name: "模型8",
    type: "模型",
    desc: "这是一个场景",
    imgUrl: " ",
  },
];
