/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const MarkLazyImport = createFileRoute('/mark')()
const AddMeshLazyImport = createFileRoute('/addMesh')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const MarkLazyRoute = MarkLazyImport.update({
  id: '/mark',
  path: '/mark',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/mark.lazy').then((d) => d.Route))

const AddMeshLazyRoute = AddMeshLazyImport.update({
  id: '/addMesh',
  path: '/addMesh',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/addMesh.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/addMesh': {
      id: '/addMesh'
      path: '/addMesh'
      fullPath: '/addMesh'
      preLoaderRoute: typeof AddMeshLazyImport
      parentRoute: typeof rootRoute
    }
    '/mark': {
      id: '/mark'
      path: '/mark'
      fullPath: '/mark'
      preLoaderRoute: typeof MarkLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/addMesh': typeof AddMeshLazyRoute
  '/mark': typeof MarkLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/addMesh': typeof AddMeshLazyRoute
  '/mark': typeof MarkLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/addMesh': typeof AddMeshLazyRoute
  '/mark': typeof MarkLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/addMesh' | '/mark'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/addMesh' | '/mark'
  id: '__root__' | '/' | '/about' | '/addMesh' | '/mark'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  AddMeshLazyRoute: typeof AddMeshLazyRoute
  MarkLazyRoute: typeof MarkLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  AddMeshLazyRoute: AddMeshLazyRoute,
  MarkLazyRoute: MarkLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/addMesh",
        "/mark"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/addMesh": {
      "filePath": "addMesh.lazy.tsx"
    },
    "/mark": {
      "filePath": "mark.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
